config/routes.rb
Rails.application.routes.draw do
  resources :bands
  resources :events
  resources :concert_halls

end

app/models/band.rb
class Band < ActiveRecord::Base
	has_many :events
	
	after_initialize :default_values
	
	def default_values
		self.explicit_lyrics = false
	end
end

app/models/concert_hall.rb
class ConcertHall < ActiveRecord::Base
	has_many :events
	has_many :bands, through: :events
	
	after_initialize :default_values
	
	def default_values
		self.family_friendly = false
	end
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :band
	belongs_to :concert_hall
	
	after_initialize :default_values
	
	def default_values
		self.alcohol_served = true
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy]

  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.html { redirect_to concert_halls_path, notice: 'Band was successfully created.' }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1
  # PATCH/PUT /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to @band, notice: 'Band was successfully updated.' }
        format.json { render :show, status: :ok, location: @band }
      else
        format.html { render :edit }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band.destroy
    respond_to do |format|
      format.html { redirect_to bands_url, notice: 'Band was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_params
      params.require(:band).permit(:name, :genre, :explicit_lyrics)
    end
end

app/controllers/concert_halls_controller.rb
class ConcertHallsController < ApplicationController
  before_action :set_concert_hall, only: [:show, :edit, :update, :destroy]

  # GET /concert_halls
  # GET /concert_halls.json
  def index
    @concert_halls = ConcertHall.all
  end

  # GET /concert_halls/1
  # GET /concert_halls/1.json
  def show
    @event = Event.new
  end

  # GET /concert_halls/new
  def new
    @concert_hall = ConcertHall.new
  end

  # GET /concert_halls/1/edit
  def edit
  end

  # POST /concert_halls
  # POST /concert_halls.json
  def create
    @concert_hall = ConcertHall.new(concert_hall_params)

    respond_to do |format|
      if @concert_hall.save
        format.html { redirect_to @concert_hall, notice: 'Concert hall was successfully created.' }
        format.json { render :show, status: :created, location: @concert_hall }
      else
        format.html { render :new }
        format.json { render json: @concert_hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concert_halls/1
  # PATCH/PUT /concert_halls/1.json
  def update
    respond_to do |format|
      if @concert_hall.update(concert_hall_params)
        format.html { redirect_to @concert_hall, notice: 'Concert hall was successfully updated.' }
        format.json { render :show, status: :ok, location: @concert_hall }
      else
        format.html { render :edit }
        format.json { render json: @concert_hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concert_halls/1
  # DELETE /concert_halls/1.json
  def destroy
    @concert_hall.destroy
    respond_to do |format|
      format.html { redirect_to concert_halls_url, notice: 'Concert hall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert_hall
      @concert_hall = ConcertHall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concert_hall_params
      params.require(:concert_hall).permit(:name, :city, :state, :family_friendly)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index

    if(params[:date])
      @events = Event.where(date:params[:date]) 
      render :index
    else 
      @events = Event.all
    end

  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to concert_hall_path(event_params[:concert_hall_id]), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def search
  #   day = params[:date]
  #   @events = Event.find_by({date: "#{day}"})
  #   render :show
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date, :alcohol_served, :band_id, :concert_hall_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/concert_halls_helper.rb
module ConcertHallsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/bands/new.html.erb
<h1> Create A New Band Below: </h1>

<%= form_for @band do |f| %>
	<%= f.text_field :name, placeholder: "Name" %></br>
	<%= f.text_field :genre, placeholder: "Genre" %></br>
	<%= f.label(:explicit_lyrics, "Explicit Lyrics?") %>
	<%= f.check_box(:explicit_lyrics) %> </br>
	<%= f.submit %>

<% end %>

app/views/concert_halls/index.html.erb
<h1> Check Out Your Favorite Venue: </h1>

<% @concert_halls.each do |x| %>

<h2> <%= link_to x.name, concert_hall_path(x.id) %> </h2>
<h3> Location: <%= x.city %>, <%= x.state %> </h3>
<% end %>


<h3> <%= link_to "Create New Venue Here", new_concert_hall_path %> </h3>
<h3> <%= link_to "Create New Band Here", new_band_path %> </h3>

app/views/concert_halls/new.html.erb
new.html.erb

<h1> Create A New Venue Below: </h1>

<%= form_for @concert_hall do |f| %>
	<%= f.text_field :name, placeholder: "Name" %></br>
	<%= f.text_field :city, placeholder: "City" %></br>
	<%= f.text_field :state, placeholder: "State" %></br>
	<%= f.label(:family_friendly, "Family Friendly?") %>
	<%= f.check_box(:family_friendly) %> </br>
	<%= f.submit %>

<% end %>

app/views/concert_halls/show.html.erb
<h1> <%= @concert_hall.name %> </h1>

<% @concert_hall.events.each do |x| %>

<h3> <%= x.band.name %> </h3>
<h4> <%= x.date %> </h4>
<h4> Alcohol Served: <%= x.alcohol_served %></h4>
<% end %></br>

<h2> Add New Event Below: </h2>

<%= form_for @event do |f| %>
	<%= f.date_field :date %>
	<%= f.label(:alcohol_served, "Alcohol Served?") %>
	<%= f.check_box(:alcohol_served) %> </br>
	<%= f.hidden_field :concert_hall_id, value: @concert_hall.id %>
	Band: <%= f.collection_select :band_id, Band.all, :id, :name %> </br>
	<%= f.submit %>

<% end %>

app/views/events/index.html.erb
<h1> All Events: </h1>

<% @events.each do |x| %>

<h2> <%= x.date %> | <%= x.band.name %> | <%= x.concert_hall.name %> </h2>
<h3> Alcohol Served: <%= x.alcohol_served %></h3>
<% end %>


<%= form_tag '/events', method: :get %>
	<%= date_field_tag "date" %>
	<%= submit_tag("Search") %>
	<%= hidden_field_tag :id, value: 1 %> 

app/views/events/show.html.erb
<h1> Events On <%= @events[0].date %>: </h1>

<% @events.each do |x| %>

<h2> <%= x.band.name %> </h2>
<h3> Alcohol Served: <%= x.alcohol_served %></h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Venue</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>